# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-20 19:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_contato', models.CharField(max_length=50)),
                ('telefone_contato', models.CharField(max_length=50)),
                ('email_contato', models.CharField(max_length=50)),
                ('tipo_anuncio', models.CharField(choices=[('Venda', 'Venda'), ('Aluguel', 'Aluguel')], max_length=40)),
                ('created', models.DateField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('quartos', models.IntegerField()),
                ('banheiros', models.IntegerField()),
                ('suites', models.IntegerField()),
                ('area_construida', models.DecimalField(decimal_places=2, max_digits=9)),
                ('area_total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('tipo_imovel', models.CharField(choices=[('Apartamento', 'Apartamento'), ('Casa', 'Casa'), ('Comercial', 'Comercial'), ('Fazenda/Sítio', 'Fazenda/Sítio')], max_length=30)),
                ('data_construcao', models.DateField(null=True)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=9)),
                ('preco_aluguel', models.DecimalField(decimal_places=2, max_digits=9)),
                ('pais', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('rua', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=50)),
                ('pagamento', models.BooleanField(default=False)),
                ('publicado', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios_do_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
