# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-22 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0005_auto_20161121_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
    ]
