# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-05 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0006_anuncio_destaque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='created',
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='cidade',
            field=models.CharField(choices=[('Macaé', 'Macaé'), ('Rio das Ostras', 'Rio das Ostras'), ('Campos', 'Campos'), ('Búzios', 'Búzios')], max_length=50),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='data_construcao',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='tipo_anuncio',
            field=models.CharField(choices=[('Venda', 'Venda'), ('Aluguel', 'Aluguel'), ('Aluguel e Venda', 'Aluguel e Venda')], max_length=40),
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='titulo',
            field=models.CharField(max_length=300),
        ),
    ]
